const VisualConfigurationActionTypes = {
    TOGGLE_VISUAL_CONFIGURATION_PANEL_HIDDEN: 'TOGGLE_VISUAL_CONFIGURATION_PANEL_HIDDEN',
    SET_VISUAL_CONFIGURATION_PANEL_HIDDEN: 'SET_VISUAL_CONFIGURATION_PANEL_HIDDEN',
    SET_VISUAL_CONFIGURATION_PANEL_VISIBLE: 'SET_VISUAL_CONFIGURATION_PANEL_VISIBLE',
    SET_VISUAL_CONFIGURATION: 'SET_VISUAL_CONFIGURATION'

}

export default VisualConfigurationActionTypes;