const AnnotationPanelActionTypes = {
    TOGGLE_ANNOTATION_PANEL_HIDDEN: 'TOGGLE_ANNOTATION_PANEL_HIDDEN',
    SET_ANNOTATION_PANEL_VISIBLE: 'SET_ANNOTATION_PANEL_VISIBLE',
    SET_ANNOTATION_PANEL_HIDDEN: 'SET_ANNOTATION_PANEL_HIDDEN',
    SET_ANNOTATION_PANEL_EDIT_MODE: 'SET_ANNOTATION_PANEL_EDIT_MODE',
    SET_ANNOTATION_PANEL_READ_MODE: 'SET_ANNOTATION_PANEL_READ_MODE',
    SET_CURRENT_ANNOTATED_ITEM: 'SET_CURRENT_ANNOTATED_ITEM'

}

export default AnnotationPanelActionTypes;