const ArticleDirectoryActionTypes = {
    
    FETCH_ARTICLE_DIRECTORY_START: 'FETCH_ARTICLE_DIRECTORY_START',
    FETCH_ARTICLE_DIRECTORY_SUCCESS: 'FETCH_ARTICLE_DIRECTORY_SUCCESS',
    FETCH_ARTICLE_DIRECTORY_FAILURE: 'FETCH_ARTICLE_DIRECTORY_FAILURE',
    SET_CURRENT_ARTICLE_ID: 'SET_CURRENT_ARTICLE_ID'
  };
  
export default ArticleDirectoryActionTypes;