const HighlightingListActionTypes = {
    TOGGLE_ANNOTATION_LIST_PANEL_HIDDEN: 'TOGGLE_ANNOTATION_LIST_PANEL_HIDDEN',    
    ADD_SELECTION_HIGHLIGHTING: 'ADD_SELECTION_HIGHLIGHTING',
    REMOVE_SELECTION_HIGHLIGHTING: 'REMOVE_SELECTION_HIGHLIGHTING',
    ADD_PARAGRAPH_HIGHLIGHTING: 'ADD_PARAGRAPH_HIGHLIGHTING',
    REMOVE_PARAGRAPH_HIGHLIGHTING: 'REMOVE_PARAGRAPH_HIGHLIGHTING',
    ADD_ANNOTATION_DETAIL: 'ADD_ANNOTATION',
    REMOVE_ANNOTATION: 'REMOVE_ANNOTATION',
    ADD_ANNOTATION_HISTORY: 'ADD_ANNOTATION_HISTORY',
    SET_TAG_FILTER: 'SET_TAG_FILTER',
  };
  
export default HighlightingListActionTypes;