const ReadingListActionTypes = {
    TOGGLE_READING_LIST_HIDDEN: 'TOGGLE_READING_LIST_HIDDEN',
    SET_READING_LIST_HIDDEN: 'SET_READING_LIST_HIDDEN',
    ADD_ELEMENT_TO_READING_LIST: 'ADD_ELEMENT_TO_READING_LIST',    
    REMOVE_ELEMENT_FROM_READING_LIST: 'REMOVE_ELEMENT_FROM_READING_LIST'

}

export default ReadingListActionTypes;