const ReadingStatusActionTypes = {
    
    SET_CURRENT_ARTICLE: 'SET_CURRENT_ARTICLE',   
    UPDATE_PROGRESS_AT_READING_STATUS: 'UPDATE_PROGRESS_AT_READING_STATUS',
    UPDATE_PROGRESS_AT_TEXT_BLOCK_ID: 'UPDATE_PROGRESS_AT_TEXT_BLOCK_ID'
  };
  
export default ReadingStatusActionTypes;